# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --llr -Dmaven.test.skip=true
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --llr -Dmaven.test.skip=true

  release-docker-hub:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & push Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ovas04/touch-go
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: release-docker-hub
      steps:
        - name: Checkout to the branch
          uses: actions/checkout@v2

        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.CATOUCHGO_AZURE_CREDENTIALS }}

        - name: Build and push container image to registry
          uses: azure/container-apps-deploy-action@v1
          with:
            appSourcePath: ${{ github.workspace }}
            registryUrl: docker.io
            registryUsername: ${{ secrets.CATOUCHGO_REGISTRY_USERNAME }}
            registryPassword: ${{ secrets.CATOUCHGO_REGISTRY_PASSWORD }}
            containerAppName: ca-touchgo
            resourceGroup: rg_student
            imageToBuild: ovas04/ca-touchgo:${{ github.sha }}
            dockerfilePath: Dockerfile