# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'
      - '.github/workflows/touch-go-AutoDeployTrigger-a4ebca7e-e14a-4a7b-ad48-67e319bd7384.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --llr -Dmaven.test.skip=true
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --llr -Dmaven.test.skip=true
  release-docker-hub:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & push Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ovas04/touch-go
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-and-push-azure:
    name: build-and-push-acr
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Tag image
        run: |
          docker build -f ./Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/touch-go:${{ github.run_number }} .
      - name: Push image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/touch-go:${{ github.run_number }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-azure
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TOUCHGO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: crtouchgo.azurecr.io
          registryUsername: ${{ secrets.TOUCHGO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TOUCHGO_REGISTRY_PASSWORD }}
          containerAppName: touch-go
          resourceGroup: rg_touchgo
          imageToBuild: crtouchgo.azurecr.io/touch-go:${{ github.sha }}